### ISSUE TITLE
Edition icon in tags does not show 

### ISSUE THREAD

**Issue by belbiy** [magento-devdocs/devdocs-theme#85]
Edition icon in `Spectrum-Tags` contains relative path to the current URL:

```
./../assets/i/ee-only.svg
```

Probably should be:

```
../assets/i/ee-only.svg
```

**Comment by leslietilling** [comment]
![image](https://user-images.githubusercontent.com/1128913/129753387-03cfffbf-edba-4f19-8195-c23b7ea6c6a0.png)

**Comment by dshevtsov** [comment]
@leslietilling please post a link to the broken page
